# FROM clearwater/base
FROM docker.io/tangfeixiong/clearwater-base-onbuild:1611180614.gitrev-c2da9c9
MAINTAINER tangfeixiong<tangfx128@gmail.com>
# Inspired by: maintainers@projectclearwater.org

ADD *supervisord.conf /etc/supervisor/conf.d/

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes bono \
  && sed -e 's/\(echo 0 > \/proc\/sys\/kernel\/yama\/ptrace_scope\)/# \0/g' -i /etc/init.d/bono \
  && apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes restund \
  && sed -e 's/\(echo 0 > \/proc\/sys\/kernel\/yama\/ptrace_scope\)/# \0/g' -i /etc/init.d/restund \
  && mv /etc/supervisor/conf.d/bono.supervisord.conf /etc/supervisor/conf.d/bono.conf \
  && mv /etc/supervisor/conf.d/restund.supervisord.conf /etc/supervisor/conf.d/restund.conf \
  && mv /etc/supervisor/conf.d/clearwater-group.supervisord.conf /etc/supervisor/conf.d/clearwater-group.conf \
  && rm -rf /var/lib/apt/lists/*

EXPOSE 3478 3478/udp 5058 5060 5060/udp 5062
