apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: cassandra
  name: cassandra
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      service: cassandra
  template:
    metadata:
      labels:
        service: cassandra
    spec:
      containers:
      - image: "docker.io/tangfeixiong/clearwater-cassandra:1611180614.gitrev-c2                                                                                                                                                                                               da9c9"
        name: cassandra
        ports:
        - containerPort: 22
        - containerPort: 7001
        - containerPort: 9042
        - containerPort: 9160
        env:
        - name: ETCD_PROXY
          value: default=http://10.64.33.81:2380
        # - name: ZONE
        #   value: clearwater.local
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        # livenessProbe:
        #   exec:
        #     command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "7000                                                                                                                                                                                                9042 9160"]
        #   initialDelaySeconds: 30
        # readinessProbe:
        #   exec:
        #     command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "7000                                                                                                                                                                                                9042 9160"]
      restartPolicy: Always
