apiVersion: v1
kind: Service
metadata:
  name: ellis
  namespace: default
spec:
  ports:
  - name: "80"
    port: 80
    nodePort: 32180
    targetPort: 80
  selector:
    service: ellis
  type: NodePort