apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: etcd
  name: etcd
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: etcd
  template:
    metadata:
      labels:
        service: etcd
    spec:
      containers:
      - args:
        - -name
        - etcd0
        - -advertise-client-urls
        - http://etcd:2379,http://etcd:4001
        - -listen-client-urls
        - http://0.0.0.0:2379,http://0.0.0.0:4001
        - -initial-advertise-peer-urls
        - http://etcd:2380
        - -listen-peer-urls
        - http://0.0.0.0:2380
        - -initial-cluster
        - etcd0=http://etcd:2380
        - -initial-cluster-state
        - new
        image: quay.io/coreos/etcd:v2.2.5
        name: etcd
        ports:
        - containerPort: 2379
        - containerPort: 2380
        - containerPort: 4001
      restartPolicy: Always