apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2379
  - name: "4001"
    port: 4001
  - name: peer
    port: 2380
  selector:
    service: etcd