apiVersion: v1
kind: Service
metadata:
  name: homestead
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: "8888"
    port: 8888
  - name: "8889"
    port: 8889
  selector:
    service: homestead