apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: homestead
  name: homestead
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      service: homestead
  template:
    metadata:
      labels:
        service: homestead
    spec:
      containers:
      - image: 10.64.33.81:5000/admin/clearwater_homestead # docker.io/tangfeixiong/clearwater-homestead:1611280555.gitrev-3e9722f
        name: homestead
        ports:
        - containerPort: 22
        - containerPort: 8888
        - containerPort: 8889
        env:
        # - name: ETCD_PROXY
        #   value: default=http://10.64.33.81:2380
        # - name: ZONE
        #   value: default.svc.cluster.local
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        # livenessProbe:
        #   exec:
        #     command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "8888 8889"]
        #   initialDelaySeconds: 30
        # readinessProbe:
        #   exec:
        #     command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "8888 8889"]
      restartPolicy: Always