apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: homer
  name: homer
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      service: homer
  template:
    metadata:
      labels:
        service: homer
    spec:
      containers:
      - image: 10.64.33.81:5000/admin/clearwater_homer # docker.io/tangfeixiong/clearwater-homer:1611280555.gitrev-3e9722f
        name: homer
        ports:
        - containerPort: 22
        - containerPort: 7888
        env:
        # - name: ETCD_PROXY
        #   value: default=http://10.64.33.81:2380
        # - name: ZONE
        #   value: default.svc.cluster.local
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        # livenessProbe:
        #   tcpSocket:
        #     port: 7888
        #   initialDelaySeconds: 30
        # readinessProbe:
        #   tcpSocket:
        #     port: 7888
      restartPolicy: Always