apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: memcached
  name: memcached
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      service: memcached
  template:
    metadata:
      labels:
        service: memcached
    spec:
      containers:
      - image: docker.io/tangfeixiong/clearwater-memcached:1611180614.gitrev-c2da9c9
        name: memcached
        ports:
        - containerPort: 22
        - containerPort: 11211
        env:
        - name: ETCD_PROXY
          value: default=http://10.64.33.81:2380
        # - name: ZONE
        #   value: clearwater.local
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 11211
      restartPolicy: Always
