apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: "11211"
    port: 11211
  selector:
    service: memcached
[tangfx@localhost k8s-manifests]$ cat ralf-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: ralf
  name: ralf
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      service: ralf
  template:
    metadata:
      labels:
        service: ralf
    spec:
      containers:
      - image: 10.64.33.81:5000/admin/clearwater_ralf # docker.io/tangfeixiong/clearwater-ralf:1611280555.gitrev-3e9722f
        name: ralf
        ports:
        - containerPort: 22
        - containerPort: 10888
        env:
        # - name: ETCD_PROXY
        #   value: default=http://10.64.33.81:2380
        # - name: ZONE
        #   value: default.svc.cluster.local
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        # livenessProbe:
        #   tcpSocket:
        #     port: 10888
        #   initialDelaySeconds: 30
        # readinessProbe:
        #   tcpSocket:
        #     port: 10888
      restartPolicy: Always