apiVersion: v1
kind: Service
metadata:
  name: sprout
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: icscf
    port: 5052
  - name: scscf
    port: 5054
  selector:
    service: sprout