apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: sprout
  name: sprout
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      service: sprout
  template:
    metadata:
      labels:
        service: sprout
    spec:
      containers:
      - image: 10.64.33.81:5000/admin/clearwater_sprout # docker.io/tangfeixiong/clearwater-sprout:1611280555.gitrev-3e9722f
        name: sprout
        ports:
        - containerPort: 22
        - containerPort: 5052
        - containerPort: 5054
        env:
        # - name: ETCD_PROXY
        #   value: default=http://10.64.33.81:2380
        # - name: ZONE
        #   value: default.svc.cluster.local
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        # livenessProbe:
        #   exec:
        #     command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "5052 5054"]
        #   initialDelaySeconds: 30
        # readinessProbe:
        #   exec:
        #     command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "5052 5054"]
      restartPolicy: Always