# FROM clearwater/base
FROM docker.io/tangfeixiong/clearwater-base-onbuild:1611180614.gitrev-c2da9c9
MAINTAINER tangfeixiong<tangfx128@gamil.com>
# Inspired by: maintainers@projectclearwater.org

ADD *supervisord.conf /etc/supervisor/conf.d/

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes chronos \
  && mv /etc/supervisor/conf.d/snmpd.supervisord.conf /etc/supervisor/conf.d/snmpd.conf \
  && mv /etc/supervisor/conf.d/chronos.supervisord.conf /etc/supervisor/conf.d/chronos.conf \
  && mv /etc/supervisor/conf.d/clearwater-group.supervisord.conf /etc/supervisor/conf.d/clearwater-group.conf \
  && rm -rf /var/lib/apt/lists/*

EXPOSE 7253
